#!/bin/bash


# ________________ BANNER CODE _________________
# ANSI escape code for dark bright red
DARK_BRIGHT_RED='\033[38;5;196m'
NC='\033[0m'  # Reset to default colors

echo "----------------------------------------------------------------------------
"
# ASCII art in dark bright red
echo -e "	${DARK_BRIGHT_RED}888888b.                 888  .d8888b.${NC}                    "
echo -e "	${DARK_BRIGHT_RED}888  \"88b                888 d88P  Y88b${NC}                   "
echo -e "	${DARK_BRIGHT_RED}888  .88P                888 Y88b.     ${NC}                  "
echo -e "	${DARK_BRIGHT_RED}8888888K.  888  888  .d88888  \"Y888b.    .d88b.   .d8888b${NC}  "
echo -e "	${DARK_BRIGHT_RED}888  \"Y88b 888  888 d88\" 888     \"Y88b. d8P  Y8b d88P\"${NC}    "
echo -e "	${DARK_BRIGHT_RED}888    888 888  888 888  888       \"888 88888888 888${NC}      "
echo -e "	${DARK_BRIGHT_RED}888   d88P Y88b 888 Y88b 888 Y88b  d88P Y8b.     Y88b.${NC}    "
echo -e "	${DARK_BRIGHT_RED}8888888P\"   \"Y88888  \"Y88888  \"Y8888P\"   \"Y8888   \"Y8888P${NC}"
echo "
----------------------------------------------------------------------------"

# ________________ BANNER CODE _________________




if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <filename>"
  exit 1
fi

filename="$1"

terms=(
".mlab.com password"
"AWSSecretKey"
"HEROKU_API_KEY"
"HEROKU_API_KEY"
"HOMEBREW_GITHUB_API_TOKEN"
"JEKYLL_GITHUB_TOKEN"
"OTP"
"PT_TOKEN "
"SF_USERNAME"
"SF_USERNAME"
"[WFClient] Password extension:ica"
"[WFClient] Password= extension:ica"
"access_key"
"access_token"
"algolia_admin_key"
"algolia_api_key"
"alias_pass"
"alicloud_access_key"
"amazon_secret_access_key"
"amazonaws"
"ansible_vault_password"
"aos_key"
"api keys"
"api token"
"api.googlemaps AIza"
"apiSecret"
"api_hash api_id"
"api_key"
"api_key_secret"
"api_key_sid"
"api_secret"
"api_token:"
"apidocs"
"apikey"
"app_key"
"app_secret"
"appkey"
"appkeysecret"
"application_key"
"appsecret"
"appspot"
"auth"
"auth_token"
"authentication"
"authorizationToken"
"authorization_bearer:"
"aws_access"
"aws_access_key_id"
"aws_key"
"aws_secret"
"aws_token"
"b2_app_key"
"bashrc password"
"bintray_apikey"
"bintray_gpg_password"
"bintray_key"
"bintraykey"
"bluemix_api_key"
"bluemix_pass"
"browserstack_access_key"
"bucket_password"
"bucketeer_aws_access_key_id"
"bucketeer_aws_secret_access_key"
"built_branch_deploy_key"
"bx_password"
"cache_s3_secret_key"
"cattle_access_key"
"cattle_secret_key"
"certificate_password"
"ci_deploy_password"
"client_id"
"client_secret"
"client_zpk_secret_key"
"clojars_password"
"cloud_api_key"
"cloud_watch_aws_access_key"
"cloudant_password"
"cloudflare_api_key"
"cloudflare_auth_key"
"cloudfront"
"codecov_token"
"config"
"conn.login"
"connectionstring"
"consumer_key"
"credentials"
"cypress_record_key"
"database_password"
"datadog_api_key"
"datadog_app_key"
"db_password"
"db_username"
"dbpasswd"
"dbpassword"
"dbuser"
"deploy_password"
"digitalocean_ssh_key_body"
"digitalocean_ssh_key_ids"
"docker_hub_password"
"docker_key"
"docker_pass"
"docker_passwd"
"docker_password"
"dockerhub_password"
"dockerhubpassword"
"dot-files"
"dotfiles"
"droplet_travis_password"
"dynamoaccesskeyid"
"dynamosecretaccesskey"
"elasticsearch_password"
"encryption_key"
"encryption_password"
"env.heroku_api_key"
"env.sonatype_password"
"eureka.awssecretkey"
"fabricApiSecret"
"fb_secret"
"firebase"
"flickr_api_key"
"fossa_api_key"
"ftp"
"ftp_password"
"gh_api_key"
"gh_token"
"ghost_api_key"
"github_api_key"
"github_deploy_hb_doc_pass"
"github_key"
"github_password"
"github_token"
"gitlab"
"gmail_password"
"gmail_username"
"google_maps_api_key"
"google_private_key"
"gpg_key_name"
"gpg_keyname"
"gpg_passphrase"
"herokuapp"
"https://hooks.slack.com/services/"
"internal"
"irc_pass"
"jsforce"
"jwt_client_secret_key"
"jwt_lookup_secert_key"
"jwt_web_secert_key"
"jwt_xmpp_secert_key"
"key"
"keyPassword"
"ldap_password"
"ldap_username"
"linux_signing_key"
"ll_shared_key"
"login"
"lottie_happo_api_key"
"lottie_happo_secret_key"
"lottie_s3_api_key"
"lottie_s3_secret_key"
"magento password"
"mail_password"
"mailchimp"
"mailchimp_api_key"
"mailchimp_key"
"mailgun"
"mailgun apikey"
"mailgun_password"
"mailgun_priv_key"
"mailgun_secret_api_key"
"manage_key"
"mandrill_api_key"
"mapbox api key"
"master_key"
"mg_api_key"
"mg_public_api_key"
"mh_apikey"
"mh_password"
"mile_zero_key"
"minio_access_key"
"minio_secret_key"
"msg nickserv identify"
"mydotfiles"
"mysql"
"mysql password"
"mysql_root_password"
"netlify_api_key"
"nexus password"
"nexus_password"
"node_env"
"node_pre_gyp_accesskeyid"
"node_pre_gyp_secretaccesskey"
"npm_api_key"
"npm_password"
"npm_secret_key"
"npmrc _auth"
"nuget_api_key"
"nuget_apikey"
"nuget_key"
"oauth"
"oauth_token"
"object_storage_password"
"octest_app_password"
"octest_password"
"okta_key"
"omise_key"
"onesignal_api_key"
"onesignal_user_auth_key"
"openwhisk key"
"openwhisk_key"
"org_gradle_project_sonatype_nexus_password"
"org_project_gradle_sonatype_nexus_password"
"os_password"
"ossrh_jira_password"
"ossrh_pass"
"ossrh_password"
"pagerduty_apikey"
"parse_js_key"
"pass"
"passcode"
"passwd"
"password"
"password hash"
"password travis"
"passwords"
"path:sites databases password"
"pem private"
"personal_key"
"plotly_apikey"
"plugin_password"
"postgres_env_postgres_password"
"postgresql_pass"
"preprod"
"private "
"private_key"
"private_signing_password"
"prod"
"prod.access.key.id"
"prod.secret.key"
"prod_password"
"publish_key"
"pwd"
"pwds"
"rabbitmq_password"
"rds.amazonaws.com password"
"redis_password"
"rest_api_key"
"rinkeby_private_key"
"root_password"
"ropsten_private_key"
"route53_access_key_id"
"rtd_key_pass"
"rtd_store_pass"
"s3_access_key"
"s3_access_key_id"
"s3_key"
"s3_key_app_logs"
"s3_key_assets"
"s3_secret_key"
"salesforce_password"
"sandbox_aws_access_key_id"
"sandbox_aws_secret_access_key"
"sauce_access_key"
"secret"
"secret access key"
"secret.password"
"secret_access_key"
"secret_key"
"secret_key_base"
"secret_token"
"secretaccesskey"
"secretkey"
"secrets"
"secure"
"security_credentials"
"send.keys"
"send_keys"
"sendgrid_api_key"
"sendgrid_key"
"sendgrid_password"
"sendkeys"
"ses_access_key"
"ses_secret_key"
"setdstaccesskey"
"setsecretkey"
"sf_username"
"signing_key_password"
"signing_key_secret"
"slack_api"
"slack_token"
"slash_developer_space_key"
"snoowrap_password"
"socrata_password"
"sonar_organization_key"
"sonar_project_key"
"sonatype_password"
"sonatype_token_password"
"soundcloud_password"
"sql_password"
"sqsaccesskey"
"ssh"
"ssh2_auth_password"
"sshpass"
"staging"
"stg"
"storePassword"
"stormpath_api_key_id"
"stormpath_api_key_secret"
"strip_secret_key"
"stripe"
"svn_pass"
"swagger"
"tesco_api_key"
"tester_keys_password"
"testuser"
"thera_oss_access_key"
"token"
"twilio_api_key"
"twine_password"
"user auth"
"user_pass"
"user_password"
"x-api-key"
"xoxb "
"xoxp"
"xoxp OR xoxb"

)

for term in "${terms[@]}"; do
  grep -F -e "$term" "$filename"
done
